[workspace]
resolver = "2"
package = { version = "0.1.0", edition = "2024" }
metadata.crane.name="my-workspace"
members = [
    "apps/*",
    "libs/*",
]



[workspace.dependencies]
# OWN LIBS
todo-core = { path = "libs/core" }

# taskchampion = { git = "https://github.com/GothenburgBitFactory/taskchampion" }
# iroh = { version = "0.15.0" } # Removed unused iroh
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }