[package]
name = "op_crdt"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
uuid.workspace = true
chrono.workspace = true


# serde = { workspace = true, features = ["derive"] }
# tokio = { workspace = true }
# uuid = { version = "1.8.0", features = ["v4", "serde"] }
# chrono = { version = "0.4.38", features = ["serde"] }
# dson = { version = "0.3.0", default-features = false, features = ["json", "serde"] }
