-- Managed tags: a tag owned by a workflow recipe (created when its
-- automation is enabled, removed when disabled). `NULL` = ordinary tag.
-- #[toasty::breakpoint]
ALTER TABLE tags ADD COLUMN "managed_by_recipe_id" INTEGER;
-- Trip items: tasks generated by the travel-checklists managed tag carry
-- which trip they belong to and which checklist section they are in.
-- #[toasty::breakpoint]
ALTER TABLE tasks ADD COLUMN "trip_id" INTEGER;
-- #[toasty::breakpoint]
ALTER TABLE tasks ADD COLUMN "trip_section" TEXT;
-- #[toasty::breakpoint]
CREATE TABLE trips (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "tag_id" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "days" TEXT NOT NULL,
    "activities" TEXT NOT NULL,
    "created_at" TEXT NOT NULL
);