[package]
name = "mini-gpui"
version.workspace = true
edition.workspace = true

[dependencies]
storage = { path = "../../libs/storage" }
tokio = { workspace = true, features = ["sync", "rt"] }
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

gpui = { package = "gpui-pre", version = "0.3.4" }
gpui_platform = { package = "gpui-pre-platform", version = "0.3.4", features = ["font-kit"] }
gpui_tokio = { path = "../../libs/gpui-tokio" }
gpui-component = "0.6.1"
