[package]
name = "todo-2"
version.workspace = true
edition.workspace = true

[dependencies]
storage = { path = "../../libs/storage" }
tokio = { workspace = true, features = ["sync", "rt"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
reqwest.workspace = true
jiff = "0.2"
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

gpui = { package = "gpui-pre", version = "0.3.4" }
gpui_platform = { package = "gpui-pre-platform", version = "0.3.4", features = [
  "font-kit",
] }
gpui_tokio = { path = "../../libs/gpui-tokio" }
gpui-component = "0.6.1"
gpui-component-assets = { package = "gpui-kit-assets", version = "0.6.1" }
