[package]
name = "storage"
version = "0.1.0"
edition = "2024"

[dependencies]
snafu.workspace = true
turso = { version = "0.7.0-pre.1", features = ["sync"] }
tokio.workspace = true
turso-migrate = { git = "https://github.com/maun/turso-migrate.git" }
serde.workspace = true
serde_json.workspace = true
chrono = { workspace = true, features = ["serde"] }
